/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Confirm that the API process is alive without checking dependencies. */
    get: operations['getLiveness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Confirm that the API can serve traffic and required dependencies are available. */
    get: operations['getReadiness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/catalog/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List published product color variants. */
    get: operations['listCatalogProducts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/catalog/products/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a published product by slug. */
    get: operations['getCatalogProduct'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/catalog/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List published catalog categories in display order. */
    get: operations['listCatalogCategories'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/catalog/categories/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get one published category and its published product cards. */
    get: operations['getCatalogCategory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/catalog/outfits': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List published outfits. */
    get: operations['listCatalogOutfits'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/catalog/outfits/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getCatalogOutfit'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/otp/challenges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start or rate-limit a mobile OTP challenge. */
    post: operations['createOtpChallenge'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/otp/verifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify an OTP and create/rotate a secure session. */
    post: operations['verifyOtpChallenge'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke the current session. */
    delete: operations['deleteSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getCurrentCustomer'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateCurrentCustomer'];
    trace?: never;
  };
  '/me/addresses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listCurrentCustomerAddresses'];
    put?: never;
    post: operations['createCurrentCustomerAddress'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/addresses/{addressId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete one address owned by the current customer. */
    delete: operations['deleteCurrentCustomerAddress'];
    options?: never;
    head?: never;
    /** Replace one address owned by the current customer. */
    patch: operations['updateCurrentCustomerAddress'];
    trace?: never;
  };
  '/me/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listCurrentCustomerOrders'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/orders/{orderNumber}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getCurrentCustomerOrder'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/returns': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listCurrentCustomerReturns'];
    put?: never;
    /** Submit a return request within 24 hours after confirmed delivery. */
    post: operations['createCurrentCustomerReturn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cart': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getCart'];
    put?: never;
    post?: never;
    delete: operations['clearCart'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cart/lines': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['addCartLine'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/cart/lines/{lineId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove one line owned by the current cart. */
    delete: operations['deleteCartLine'];
    options?: never;
    head?: never;
    patch: operations['updateCartLine'];
    trace?: never;
  };
  '/shipping-options': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Quote eligible configured shipping methods for a cart and address. */
    get: operations['listShippingOptions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/checkout-sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reprice, validate and atomically reserve cart components. */
    post: operations['createCheckoutSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/checkout-sessions/{checkoutSessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getCheckoutSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/checkout-sessions/{checkoutSessionId}/payment-attempts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start payment through the configured provider. */
    post: operations['createPaymentAttempt'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/payment-callbacks/{provider}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Provider callback; provider-specific signature is required. */
    post: operations['processPaymentCallback'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List categories for catalog administration. */
    get: operations['listAdminCategories'];
    put?: never;
    /** Create a draft or published catalog category. */
    post: operations['createAdminCategory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/media': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List reusable media metadata. */
    get: operations['listAdminMedia'];
    put?: never;
    /** Register reusable media metadata. */
    post: operations['createAdminMedia'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['listAdminProducts'];
    put?: never;
    post: operations['createAdminProduct'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/products/{productId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminProduct'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateAdminProduct'];
    trace?: never;
  };
  '/admin/products/{productId}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['publishAdminProduct'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/products/{productId}/validation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Validate a product aggregate for publication. */
    get: operations['validateAdminProduct'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/products/{productId}/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Preview a product without exposing it publicly. */
    get: operations['previewAdminProduct'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/skus/{skuId}/prices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Append a SKU price and update its current projection. */
    post: operations['createAdminSkuPrice'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/products/{productId}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['archiveAdminProduct'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/inventory/{skuId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminInventory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/inventory/{skuId}/actions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['createAdminInventoryAction'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/returns/{returnId}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['approveAdminReturn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/returns/{returnId}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['rejectAdminReturn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/homepage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminHomepage'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateAdminHomepage'];
    trace?: never;
  };
  '/admin/settings/shipping': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['getAdminShippingSettings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['updateAdminShippingSettings'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthStatus: {
      /** @constant */
      status: 'ok';
      /** Format: uuid */
      correlationId: string;
    };
    HealthUnavailable: {
      /** @constant */
      status: 'unavailable';
      /** Format: uuid */
      correlationId: string;
    };
    /** @enum {string} */
    PublicationStatus: 'draft' | 'published' | 'archived';
    Money: {
      /**
       * Format: int64
       * @description Authoritative integer amount in Iranian rials.
       */
      amountRial: number;
      /** @constant */
      currency: 'IRR';
      /** @description Localized display string, such as a toman presentation. */
      display: string;
    };
    /** @description Normalized Iranian mobile number in E.164 form. */
    Mobile: string;
    CategorySummary: {
      /** Format: uuid */
      id: string;
      slug: string;
      name: string;
      description: string | null;
      displayOrder: number;
    };
    CategoryPage: {
      items: components['schemas']['CategorySummary'][];
    };
    CategoryDetail: components['schemas']['CategorySummary'] & {
      products: components['schemas']['ProductCardPage'];
      seo: components['schemas']['Seo'];
    };
    Media: {
      /** Format: uuid */
      id: string;
      /** Format: uri-reference */
      url: string;
      width: number;
      height: number;
      alt: string;
      focalPoint: {
        x: number;
        y: number;
      };
    };
    ProductCard: {
      /** Format: uuid */
      productId: string;
      slug: string;
      name: string;
      selectedVariant: components['schemas']['ColorVariantSummary'];
      availableColors: components['schemas']['ColorSwatch'][];
      price: components['schemas']['Money'];
      available: boolean;
    };
    ProductCardPage: {
      items: components['schemas']['ProductCard'][];
      page: components['schemas']['CursorPage'];
    };
    CursorPage: {
      nextCursor?: string | null;
      hasMore: boolean;
    };
    ColorSwatch: {
      /** Format: uuid */
      variantId: string;
      name: string;
      hex?: string | null;
      available: boolean;
    };
    ColorVariantSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      featuredMedia: components['schemas']['Media'];
    };
    SkuOption: {
      /** Format: uuid */
      id: string;
      code: string;
      size: string;
      available: boolean;
      price: components['schemas']['Money'];
    };
    ProductDetail: components['schemas']['ProductCard'] & {
      description: string;
      details?: string[];
      variants: {
        /** Format: uuid */
        id: string;
        name: string;
        gallery: components['schemas']['Media'][];
        skus: components['schemas']['SkuOption'][];
      }[];
      categories: components['schemas']['CategorySummary'][];
      seo: components['schemas']['Seo'];
      /** Format: date-time */
      updatedAt: string;
    };
    OutfitCard: {
      /** Format: uuid */
      id: string;
      slug: string;
      name: string;
      featuredMedia: components['schemas']['Media'];
      startingPrice: components['schemas']['Money'];
    };
    OutfitCardPage: {
      items: components['schemas']['OutfitCard'][];
      page: components['schemas']['CursorPage'];
    };
    OutfitDetail: components['schemas']['OutfitCard'] & {
      /** Format: uuid */
      revisionId: string;
      description: string;
      sizes: {
        code: string;
        price: components['schemas']['Money'];
        available: boolean;
        availableQuantity: number;
      }[];
      items: {
        /** Format: uuid */
        productId: string;
        /** Format: uuid */
        variantId: string;
        name: string;
        quantity: number;
      }[];
    };
    Seo: {
      title?: string;
      description?: string;
      canonicalPath?: string;
    };
    Customer: {
      /** Format: uuid */
      id: string;
      mobile: components['schemas']['Mobile'];
      firstName?: string | null;
      lastName?: string | null;
    };
    AuthenticationResult: {
      customer: components['schemas']['Customer'];
      cart: components['schemas']['Cart'];
      mergePerformed: boolean;
    };
    AddressInput: {
      recipientName: string;
      recipientMobile: components['schemas']['Mobile'];
      province: string;
      city: string;
      addressLine: string;
      postalCode: string;
      /** @default false */
      isDefault: boolean;
    };
    Address: components['schemas']['AddressInput'] & {
      /** Format: uuid */
      id: string;
    };
    AddressSnapshot: {
      recipientName: string;
      recipientMobile: components['schemas']['Mobile'];
      province: string;
      city: string;
      addressLine: string;
      postalCode: string;
      normalizedZone?: string | null;
    };
    /** @enum {string} */
    ShippingMethodCode: 'iran_post' | 'tipax' | 'tehran_local_courier';
    ShippingOption: {
      method: components['schemas']['ShippingMethodCode'];
      name: string;
      eligible: boolean;
      ineligibilityCode?: string | null;
      quotedPrice: components['schemas']['Money'];
      eligibilitySubtotal: components['schemas']['Money'];
      freeShippingApplied: boolean;
      settingsVersion: number;
    };
    ShippingSettingsInput: {
      /**
       * @description Products and Outfits only; excludes shipping, discounts, and taxes.
       * @constant
       */
      eligibilityBasis: 'order_subtotal';
      methods: {
        code: components['schemas']['ShippingMethodCode'];
        enabled: boolean;
        fixedPriceRial: number;
      }[];
      /** @description Compared with Order Subtotal. */
      freeShippingThresholdRial?: number | null;
    };
    ShippingSettings: components['schemas']['ShippingSettingsInput'] & {
      version: number;
      /** Format: date-time */
      effectiveAt: string;
    };
    ProductCartLineInput: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'ProductCartLineInput';
      /** Format: uuid */
      skuId: string;
      quantity: number;
    };
    OutfitCartLineInput: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: 'OutfitCartLineInput';
      /** Format: uuid */
      outfitRevisionId: string;
      size: string;
      quantity: number;
    };
    Cart: {
      /** Format: uuid */
      id: string;
      version: number;
      lines: {
        /** Format: uuid */
        id: string;
        /** @enum {string} */
        kind: 'product' | 'outfit';
        title: string;
        selection?: string;
        skuCode?: string | null;
        image?: components['schemas']['Media'] | null;
        quantity: number;
        /** @enum {string} */
        status: 'available' | 'unavailable' | 'requires_review';
        checkoutBlocking: boolean;
        unitPrice: components['schemas']['Money'];
      }[];
      informationalTotal: components['schemas']['Money'];
      checkoutBlocked: boolean;
      mergeNotices: {
        /** Format: uuid */
        id: string;
        /** @enum {string} */
        code:
          'quantity_reduced_to_inventory' | 'sku_unavailable' | 'outfit_revision_requires_review';
        /** Format: uuid */
        lineId: string;
        requestedQuantity?: number | null;
        appliedQuantity?: number | null;
      }[];
    };
    CheckoutSession: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      status: 'active' | 'payment_pending' | 'paid' | 'expired' | 'cancelled' | 'reconciliation';
      /** Format: date-time */
      expiresAt: string;
      quote: {
        itemsTotal: components['schemas']['Money'];
        shippingTotal: components['schemas']['Money'];
        payableTotal: components['schemas']['Money'];
      };
      shipping: components['schemas']['ShippingOption'];
    };
    PaymentAttempt: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      status: 'created' | 'redirected' | 'verified' | 'failed' | 'reconciliation';
      /** Format: uri */
      redirectUrl?: string | null;
    };
    OrderPage: {
      items: components['schemas']['OrderSummary'][];
      page: components['schemas']['CursorPage'];
    };
    OrderSummary: {
      orderNumber: string;
      /** Format: date-time */
      createdAt: string;
      /** @enum {string} */
      fulfillmentStatus: 'paid' | 'preparing' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
      paidTotal: components['schemas']['Money'];
    };
    Order: components['schemas']['OrderSummary'] & {
      items: {
        title: string;
        selection?: string;
        quantity: number;
        unitPrice: components['schemas']['Money'];
      }[];
      address: components['schemas']['AddressSnapshot'];
      shipping: {
        method: components['schemas']['ShippingMethodCode'];
        name: string;
        chargedPrice: components['schemas']['Money'];
        freeShippingApplied: boolean;
        settingsVersion: number;
      };
    };
    /** @enum {string} */
    ReturnStatus: 'submitted' | 'approved' | 'rejected' | 'completed';
    ReturnRequestInput: {
      orderNumber: string;
      items: {
        /** Format: uuid */
        orderItemId: string;
        quantity: number;
      }[];
      reason: string;
      /** @constant */
      unused: true;
      /** @constant */
      unwashed: true;
      /** @constant */
      tagsAttached: true;
    };
    ReturnRequest: components['schemas']['ReturnRequestInput'] & {
      /** Format: uuid */
      id: string;
      status: components['schemas']['ReturnStatus'];
      /** Format: date-time */
      requestedAt: string;
      /** Format: date-time */
      deliveryConfirmedAt: string;
      /** Format: date-time */
      eligibilityDeadline: string;
    };
    ReturnDecisionInput: {
      reason: string;
    };
    Inventory: {
      /** Format: uuid */
      skuId: string;
      physicalQuantity: number;
      reservedQuantity: number;
      availableQuantity: number;
      version: number;
    };
    AdminCategoryInput: {
      name: string;
      slug: string;
      description?: string | null;
      displayOrder: number;
      status?: components['schemas']['PublicationStatus'];
    };
    AdminCategory: components['schemas']['AdminCategoryInput'] & {
      /** Format: uuid */
      id: string;
      status: components['schemas']['PublicationStatus'];
      version: number;
    };
    AdminMediaInput: {
      /** Format: uri-reference */
      url: string;
      width: number;
      height: number;
      alt: string;
      /** @enum {string} */
      format: 'jpg' | 'png' | 'webp';
      /** @enum {string} */
      group: 'product_images' | 'outfit_editorial' | 'homepage' | 'journal' | 'shared_assets';
      focalPoint?: {
        x: number;
        y: number;
      };
    };
    AdminSkuInput: {
      /** Format: uuid */
      id?: string;
      code: string;
      normalizedSize: string;
      displaySize: string;
      /** Format: int64 */
      amountRial: number;
      physicalQuantity: number;
      status?: components['schemas']['PublicationStatus'];
    };
    AdminColorVariantInput: {
      /** Format: uuid */
      id?: string;
      name: string;
      normalizedColorCode: string;
      hex?: string | null;
      displayOrder: number;
      mediaIds: string[];
      /** Format: uuid */
      featuredMediaId: string;
      skus: components['schemas']['AdminSkuInput'][];
      status?: components['schemas']['PublicationStatus'];
    };
    AdminProductInput: {
      name: string;
      slug: string;
      description: string;
      categoryIds: string[];
      seo?: components['schemas']['Seo'];
      details?: string[];
      variants: components['schemas']['AdminColorVariantInput'][];
    };
    AdminProduct: components['schemas']['AdminProductInput'] & {
      /** Format: uuid */
      id: string;
      status: components['schemas']['PublicationStatus'];
      version: number;
      variants: components['schemas']['AdminColorVariantInput'][];
    };
    AdminProductPage: {
      items: components['schemas']['AdminProduct'][];
      page: components['schemas']['CursorPage'];
    };
    AdminPriceInput: {
      /** Format: int64 */
      amountRial: number;
      reason: string;
    };
    PublicationValidationError: {
      path: string;
      ruleId: string;
      message: string;
    };
    PublicationValidation: {
      valid: boolean;
      errors: components['schemas']['PublicationValidationError'][];
    };
    AdminProductPreview: {
      /** @constant */
      preview: true;
      product: components['schemas']['ProductDetail'];
    };
    Homepage: {
      version: number;
      sections: {
        /** Format: uuid */
        id: string;
        type: string;
        enabled: boolean;
        order: number;
        content: {
          [key: string]: unknown;
        };
      }[];
    };
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      detail?: string;
      /** Format: uri-reference */
      instance?: string;
      code: string;
      correlationId: string;
      errors?: {
        path: string;
        code: string;
        message: string;
      }[];
    };
  };
  responses: {
    /** @description RFC 9457-style problem response. */
    Problem: {
      headers: {
        'X-Correlation-Id'?: string;
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: {
    PageCursor: string;
    PageSize: number;
    Slug: string;
    LineId: string;
    AddressId: string;
    CheckoutSessionId: string;
    ProductId: string;
    SkuId: string;
    ReturnId: string;
    IdempotencyKey: string;
    /** @description Optimistic resource version. */
    IfMatch: string;
    /** @description Double-submit token matching the signed anti-CSRF cookie. */
    CsrfToken: string;
    /** @description Required when an anonymous-cart cookie is presented for merge. */
    OptionalCsrfToken: string;
  };
  requestBodies: never;
  headers: {
    /** @description Resolved request correlation identifier. A valid caller-supplied UUID is preserved; otherwise the API generates one. */
    CorrelationId: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getLiveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API process is alive. */
      200: {
        headers: {
          'X-Correlation-Id': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
  getReadiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API is ready to serve traffic. */
      200: {
        headers: {
          'X-Correlation-Id': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
      /** @description API is live but a required dependency is unavailable. */
      503: {
        headers: {
          'X-Correlation-Id': components['headers']['CorrelationId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthUnavailable'];
        };
      };
    };
  };
  listCatalogProducts: {
    parameters: {
      query?: {
        cursor?: components['parameters']['PageCursor'];
        limit?: components['parameters']['PageSize'];
        category?: string;
        search?: string;
        sort?: 'newest' | 'price_asc' | 'price_desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published catalog page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductCardPage'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getCatalogProduct: {
    parameters: {
      query?: {
        /** @description Optional color-variant identifier to select initially. */
        color?: string;
      };
      header?: never;
      path: {
        slug: components['parameters']['Slug'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Product detail. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductDetail'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listCatalogCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published category navigation. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryPage'];
        };
      };
      400: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  getCatalogCategory: {
    parameters: {
      query?: {
        cursor?: components['parameters']['PageCursor'];
        limit?: components['parameters']['PageSize'];
      };
      header?: never;
      path: {
        slug: components['parameters']['Slug'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published category detail. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryDetail'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listCatalogOutfits: {
    parameters: {
      query?: {
        cursor?: components['parameters']['PageCursor'];
        limit?: components['parameters']['PageSize'];
        category?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published outfit page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OutfitCardPage'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getCatalogOutfit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: components['parameters']['Slug'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published outfit detail with derived availability. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OutfitDetail'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  createOtpChallenge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          mobile: components['schemas']['Mobile'];
        };
      };
    };
    responses: {
      /** @description Generic accepted response; does not reveal account state. */
      202: {
        headers: {
          /** @description Rotated signed device and anti-CSRF cookies. */
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: uuid */
            challengeId: string;
            retryAfterSeconds: number;
            /** Format: date-time */
            expiresAt: string;
          };
        };
      };
      429: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  verifyOtpChallenge: {
    parameters: {
      query?: never;
      header?: {
        /** @description Required when an anonymous-cart cookie is presented for merge. */
        'X-CSRF-Token'?: components['parameters']['OptionalCsrfToken'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uuid */
          challengeId: string;
          code: string;
        };
      };
    };
    responses: {
      /** @description Session created or rotated and Guest Cart merge reported. */
      200: {
        headers: {
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthenticationResult'];
        };
      };
      400: components['responses']['Problem'];
      429: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  deleteSession: {
    parameters: {
      query?: never;
      header: {
        /** @description Double-submit token matching the signed anti-CSRF cookie. */
        'X-CSRF-Token': components['parameters']['CsrfToken'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  getCurrentCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current customer profile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Customer'];
        };
      };
      401: components['responses']['Problem'];
    };
  };
  updateCurrentCustomer: {
    parameters: {
      query?: never;
      header: {
        /** @description Double-submit token matching the signed anti-CSRF cookie. */
        'X-CSRF-Token': components['parameters']['CsrfToken'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          firstName?: string;
          lastName?: string;
        };
      };
    };
    responses: {
      /** @description Updated profile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Customer'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  listCurrentCustomerAddresses: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer-owned addresses. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Address'][];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  createCurrentCustomerAddress: {
    parameters: {
      query?: never;
      header: {
        /** @description Double-submit token matching the signed anti-CSRF cookie. */
        'X-CSRF-Token': components['parameters']['CsrfToken'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddressInput'];
      };
    };
    responses: {
      /** @description Address created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Address'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  deleteCurrentCustomerAddress: {
    parameters: {
      query?: never;
      header: {
        /** @description Double-submit token matching the signed anti-CSRF cookie. */
        'X-CSRF-Token': components['parameters']['CsrfToken'];
      };
      path: {
        addressId: components['parameters']['AddressId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer-owned address deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  updateCurrentCustomerAddress: {
    parameters: {
      query?: never;
      header: {
        /** @description Double-submit token matching the signed anti-CSRF cookie. */
        'X-CSRF-Token': components['parameters']['CsrfToken'];
      };
      path: {
        addressId: components['parameters']['AddressId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddressInput'];
      };
    };
    responses: {
      /** @description Customer-owned address updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Address'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listCurrentCustomerOrders: {
    parameters: {
      query?: {
        cursor?: components['parameters']['PageCursor'];
        limit?: components['parameters']['PageSize'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer-owned order summaries. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderPage'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getCurrentCustomerOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orderNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer-owned order detail. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Order'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listCurrentCustomerReturns: {
    parameters: {
      query?: {
        cursor?: components['parameters']['PageCursor'];
        limit?: components['parameters']['PageSize'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Customer-owned return requests. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['ReturnRequest'][];
            page: components['schemas']['CursorPage'];
          };
        };
      };
      default: components['responses']['Problem'];
    };
  };
  createCurrentCustomerReturn: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReturnRequestInput'];
      };
    };
    responses: {
      /** @description Return request submitted for administrator review. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReturnRequest'];
        };
      };
      409: components['responses']['Problem'];
      422: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  getCart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current cart with informational prices and availability. */
      200: {
        headers: {
          /** @description Anonymous-cart and anti-CSRF cookies when absent or rotated. */
          'Set-Cookie'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Cart'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  clearCart: {
    parameters: {
      query?: never;
      header: {
        /** @description Optimistic resource version. */
        'If-Match': components['parameters']['IfMatch'];
        /** @description Double-submit token matching the signed anti-CSRF cookie. */
        'X-CSRF-Token': components['parameters']['CsrfToken'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cart cleared. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components['responses']['Problem'];
    };
  };
  addCartLine: {
    parameters: {
      query?: never;
      header: {
        /** @description Optimistic resource version. */
        'If-Match': components['parameters']['IfMatch'];
        /** @description Double-submit token matching the signed anti-CSRF cookie. */
        'X-CSRF-Token': components['parameters']['CsrfToken'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['ProductCartLineInput']
          | components['schemas']['OutfitCartLineInput'];
      };
    };
    responses: {
      /** @description Updated cart. Adding a line does not reserve inventory. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Cart'];
        };
      };
      409: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  deleteCartLine: {
    parameters: {
      query?: never;
      header: {
        /** @description Optimistic resource version. */
        'If-Match': components['parameters']['IfMatch'];
        /** @description Double-submit token matching the signed anti-CSRF cookie. */
        'X-CSRF-Token': components['parameters']['CsrfToken'];
      };
      path: {
        lineId: components['parameters']['LineId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Line removed. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components['responses']['Problem'];
      409: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  updateCartLine: {
    parameters: {
      query?: never;
      header: {
        /** @description Optimistic resource version. */
        'If-Match': components['parameters']['IfMatch'];
        /** @description Double-submit token matching the signed anti-CSRF cookie. */
        'X-CSRF-Token': components['parameters']['CsrfToken'];
      };
      path: {
        lineId: components['parameters']['LineId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          quantity: number;
        };
      };
    };
    responses: {
      /** @description Updated cart. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Cart'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  listShippingOptions: {
    parameters: {
      query: {
        cartId: string;
        addressId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Eligible server-calculated shipping options. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShippingOption'][];
        };
      };
      422: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  createCheckoutSession: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uuid */
          cartId: string;
          /** Format: uuid */
          addressId: string;
          deliveryMethod: components['schemas']['ShippingMethodCode'];
        };
      };
    };
    responses: {
      /** @description Checkout quote and reservations active for 30 minutes. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CheckoutSession'];
        };
      };
      409: components['responses']['Problem'];
      422: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  getCheckoutSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        checkoutSessionId: components['parameters']['CheckoutSessionId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current session status and quote. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CheckoutSession'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  createPaymentAttempt: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        checkoutSessionId: components['parameters']['CheckoutSessionId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Payment attempt created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaymentAttempt'];
        };
      };
      409: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  processPaymentCallback: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Verified callback processed idempotently. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'paid' | 'failed' | 'pending_reconciliation';
            orderNumber?: string | null;
          };
        };
      };
      400: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listAdminCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Administrative category list. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCategory'][];
        };
      };
      401: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  createAdminCategory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminCategoryInput'];
      };
    };
    responses: {
      /** @description Draft category created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCategory'];
        };
      };
      409: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listAdminMedia: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reusable media assets. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Media'][];
        };
      };
      401: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  createAdminMedia: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminMediaInput'];
      };
    };
    responses: {
      /** @description Reusable media metadata registered. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Media'];
        };
      };
      422: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  listAdminProducts: {
    parameters: {
      query?: {
        cursor?: components['parameters']['PageCursor'];
        limit?: components['parameters']['PageSize'];
        status?: components['schemas']['PublicationStatus'];
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Administrative product page. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductPage'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  createAdminProduct: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminProductInput'];
      };
    };
    responses: {
      /** @description Draft product created. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProduct'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getAdminProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        productId: components['parameters']['ProductId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Administrative product. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProduct'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  updateAdminProduct: {
    parameters: {
      query?: never;
      header: {
        /** @description Optimistic resource version. */
        'If-Match': components['parameters']['IfMatch'];
      };
      path: {
        productId: components['parameters']['ProductId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminProductInput'];
      };
    };
    responses: {
      /** @description Product updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProduct'];
        };
      };
      409: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  publishAdminProduct: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        productId: components['parameters']['ProductId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Product and eligible child state published. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProduct'];
        };
      };
      422: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  validateAdminProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        productId: components['parameters']['ProductId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Publication validation result with stable business-rule IDs. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicationValidation'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  previewAdminProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        productId: components['parameters']['ProductId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Protected storefront-shaped preview of a draft or published product. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductPreview'];
        };
      };
      404: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  createAdminSkuPrice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        skuId: components['parameters']['SkuId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminPriceInput'];
      };
    };
    responses: {
      /** @description Immutable price fact and updated current projection. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Money'];
        };
      };
      422: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  archiveAdminProduct: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        productId: components['parameters']['ProductId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Product archived without removing history. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProduct'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  getAdminInventory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        skuId: components['parameters']['SkuId'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current inventory projection. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Inventory'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  createAdminInventoryAction: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        skuId: components['parameters']['SkuId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          action: 'production' | 'instagram_sale' | 'manual_correction' | 'damaged_goods';
          quantity: number;
          reason: string;
        };
      };
    };
    responses: {
      /** @description Inventory movement and updated projection. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Inventory'];
        };
      };
      409: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  approveAdminReturn: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        returnId: components['parameters']['ReturnId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReturnDecisionInput'];
      };
    };
    responses: {
      /** @description Return approved and downstream inventory/financial workflow applied. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReturnRequest'];
        };
      };
      409: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  rejectAdminReturn: {
    parameters: {
      query?: never;
      header: {
        'Idempotency-Key': components['parameters']['IdempotencyKey'];
      };
      path: {
        returnId: components['parameters']['ReturnId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReturnDecisionInput'];
      };
    };
    responses: {
      /** @description Return rejected without inventory restoration. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReturnRequest'];
        };
      };
      409: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  getAdminHomepage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Homepage composition. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Homepage'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  updateAdminHomepage: {
    parameters: {
      query?: never;
      header: {
        /** @description Optimistic resource version. */
        'If-Match': components['parameters']['IfMatch'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Homepage'];
      };
    };
    responses: {
      /** @description Homepage saved and publicly visible. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Homepage'];
        };
      };
      409: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
  getAdminShippingSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Effective shipping configuration. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShippingSettings'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
  updateAdminShippingSettings: {
    parameters: {
      query?: never;
      header: {
        /** @description Optimistic resource version. */
        'If-Match': components['parameters']['IfMatch'];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ShippingSettingsInput'];
      };
    };
    responses: {
      /** @description New effective version of shipping settings. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShippingSettings'];
        };
      };
      409: components['responses']['Problem'];
      422: components['responses']['Problem'];
      default: components['responses']['Problem'];
    };
  };
}
